/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alerta_entrega_cch: typeof import('./src/components/alerta_entrega_cch.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    'AppHeader.1': typeof import('./src/components/AppHeader.1.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    ButtonChangeTheme: typeof import('./src/components/ButtonChangeTheme.vue')['default']
    Card_1: typeof import('./src/components/Card_1.vue')['default']
    ChartCard3: typeof import('./src/components/ChartCard3.vue')['default']
    ContaTimeline: typeof import('./src/components/ContaTimeline.vue')['default']
    copy: typeof import('./src/components/charts/faixa_etaria copy.vue')['default']
    D: typeof import('./src/components/EChartCard2.vue')['default']
    EChartCard: typeof import('./src/components/EChartCard.vue')['default']
    EChartCard2: typeof import('./src/components/EChartCard2.vue')['default']
    Faixa_empresa: typeof import('./src/components/charts/faixa_empresa.vue')['default']
    Faixa_etaria: typeof import('./src/components/charts/faixa_etaria.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select_estado: typeof import('./src/components/select_estado.vue')['default']
    Sexo_funcionarios: typeof import('./src/components/charts/sexo_funcionarios.vue')['default']
    Sexo_funcionarios__: typeof import('./src/components/charts/sexo_funcionarios.vue')['default']
    Tempo_empresa: typeof import('./src/components/charts/tempo_empresa.vue')['default']
    VisualizarPDF: typeof import('./src/components/VisualizarPDF.vue')['default']
    VisualizarPDF2: typeof import('./src/components/VisualizarPDF2.vue')['default']
  }
}
