/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/arquivo/': RouteRecordInfo<'/arquivo/', '/arquivo', Record<never, never>, Record<never, never>>,
    '/arquivo/novo': RouteRecordInfo<'/arquivo/novo', '/arquivo/novo', Record<never, never>, Record<never, never>>,
    '/arquivo/UploadFile': RouteRecordInfo<'/arquivo/UploadFile', '/arquivo/UploadFile', Record<never, never>, Record<never, never>>,
    '/campi/': RouteRecordInfo<'/campi/', '/campi', Record<never, never>, Record<never, never>>,
    '/campi/edit': RouteRecordInfo<'/campi/edit', '/campi/edit', Record<never, never>, Record<never, never>>,
    '/campi/new': RouteRecordInfo<'/campi/new', '/campi/new', Record<never, never>, Record<never, never>>,
    '/campi/view': RouteRecordInfo<'/campi/view', '/campi/view', Record<never, never>, Record<never, never>>,
    '/cchfuncionario/': RouteRecordInfo<'/cchfuncionario/', '/cchfuncionario', Record<never, never>, Record<never, never>>,
    '/cidade/': RouteRecordInfo<'/cidade/', '/cidade', Record<never, never>, Record<never, never>>,
    '/cidade/edit': RouteRecordInfo<'/cidade/edit', '/cidade/edit', Record<never, never>, Record<never, never>>,
    '/cidade/new': RouteRecordInfo<'/cidade/new', '/cidade/new', Record<never, never>, Record<never, never>>,
    '/cidade/view': RouteRecordInfo<'/cidade/view', '/cidade/view', Record<never, never>, Record<never, never>>,
    '/dashadmin/': RouteRecordInfo<'/dashadmin/', '/dashadmin', Record<never, never>, Record<never, never>>,
    '/dashfuncionario/': RouteRecordInfo<'/dashfuncionario/', '/dashfuncionario', Record<never, never>, Record<never, never>>,
    '/financeiro/banco/': RouteRecordInfo<'/financeiro/banco/', '/financeiro/banco', Record<never, never>, Record<never, never>>,
    '/financeiro/banco/edit': RouteRecordInfo<'/financeiro/banco/edit', '/financeiro/banco/edit', Record<never, never>, Record<never, never>>,
    '/financeiro/banco/new': RouteRecordInfo<'/financeiro/banco/new', '/financeiro/banco/new', Record<never, never>, Record<never, never>>,
    '/financeiro/lancamento/': RouteRecordInfo<'/financeiro/lancamento/', '/financeiro/lancamento', Record<never, never>, Record<never, never>>,
    '/financeiro/lancamento/edit': RouteRecordInfo<'/financeiro/lancamento/edit', '/financeiro/lancamento/edit', Record<never, never>, Record<never, never>>,
    '/financeiro/lancamento/new': RouteRecordInfo<'/financeiro/lancamento/new', '/financeiro/lancamento/new', Record<never, never>, Record<never, never>>,
    '/funcionario/': RouteRecordInfo<'/funcionario/', '/funcionario', Record<never, never>, Record<never, never>>,
    '/funcionario/contracheque': RouteRecordInfo<'/funcionario/contracheque', '/funcionario/contracheque', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/simulacao/': RouteRecordInfo<'/simulacao/', '/simulacao', Record<never, never>, Record<never, never>>,
    '/teste/': RouteRecordInfo<'/teste/', '/teste', Record<never, never>, Record<never, never>>,
    '/teste1/': RouteRecordInfo<'/teste1/', '/teste1', Record<never, never>, Record<never, never>>,
    '/teste2/': RouteRecordInfo<'/teste2/', '/teste2', Record<never, never>, Record<never, never>>,
    '/teste3/': RouteRecordInfo<'/teste3/', '/teste3', Record<never, never>, Record<never, never>>,
    '/uf/': RouteRecordInfo<'/uf/', '/uf', Record<never, never>, Record<never, never>>,
    '/uf/edit': RouteRecordInfo<'/uf/edit', '/uf/edit', Record<never, never>, Record<never, never>>,
    '/uf/new': RouteRecordInfo<'/uf/new', '/uf/new', Record<never, never>, Record<never, never>>,
    '/uf/view': RouteRecordInfo<'/uf/view', '/uf/view', Record<never, never>, Record<never, never>>,
  }
}
